nohup: ignoring input
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/anaconda3/envs/sdwebui/lib/python3.10/site-packages/telegram/ext/_application.py", line 1264, in process_update
    await coroutine
  File "/root/anaconda3/envs/sdwebui/lib/python3.10/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/home/AI_project/superimage/model/sendPhoto3.py", line 51, in generate_images
    if len(images) == 4:
TypeError: object of type 'coroutine' has no len()
/root/anaconda3/envs/sdwebui/lib/python3.10/site-packages/telegram/ext/_application.py:1274: RuntimeWarning: coroutine 'StableDiffusionClient.fetch_images' was never awaited
  if await self.process_error(update=update, error=exc):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
